### ISSUE TITLE
popup size constraints

### ISSUE THREAD

**Issue by BossMewing** [araten10/EdgewarePlusPlus#114] opened 2024-11-11 00:20 UTC
i remember there was an edgeware plus feature that allowed us to control how big or small popups would be using sliders to set minimum and maximum sizes.

**Comment by LewdDevelopment** [comment] 2024-11-11 07:16
Duplicate of #95

To my knowledge, this feature has never existed in any official version of Edgeware or Edgeware++, maybe you used a modified version someone else made.

**Closed by LewdDevelopment** 2024-11-11 07:16 UTC
Labels: duplicate
